### ISSUE TITLE
st-link simple example

### ISSUE THREAD

**Issue by Le0nX** [ROBOTIS-GIT/OpenCM9.04#69]
Hello! I'm new to ARM programming and couldn't find any manuals/examples on C++ programming via ST-Link for your board... Could you give some simple example of code and process of it's building with flashing OpenCM via ST-link? 

For example, I have Dynamixel ax-12a servos and want to rotate one of them with C++ bare bones on your board. Will I be able to use Dynamixel SDK for this task?

**Comment by Le0nX** [comment]
anybody?

**Comment by OpusK** [comment]
Hi, @Le0nX 

We do not officially provide a reference for this method.
However, since there is a hardware SWD pin, you can use it to create general firmware yourself.

If you use Eclipse or use TrueStudio, you can do this easily.
However, in this case, OpenCM's boot loader will be erased, which can be a bit cumbersome to repair.

**Comment by TuxLeon** [comment]
Hi Le0nX,
I was also looking for the STM source code or project. I now found this github repository. Perhaps this is what you were looking for.
https://github.com/ROBOTIS-GIT/OpenCM9.04/tree/master/arduino/opencm_arduino/opencm9.04

**Comment by OpusK** [comment]
Hi, @TuxLeon.

This is a project to create a .lib file for opencm9.04. With this eclipse project, you can not do exactly what LeOnX wants. Of course, you can refer to it to create an eclipse or TruStudio project.

**Comment by Le0nX** [comment]
Thx!
